### ISSUE TITLE
Create Spritesheets

### ISSUE THREAD

**Issue by corykitchens** [corykitchens/whoniverse#6]

**Comment by corykitchens** [comment]
@Americkan To get the current assets..
1. `git clone` the project repository
2. Follow the readme instructions to build and run
3. The assets are located in `/public/game/assets/images`
4. For the addition of sprites and/or images create a feature branch e.g. 
`git branch feature-planet-sprites`
5. Commit the files to your feature branch and push to origin
`git push origin feature-planet-sprites`

**Comment by Americkan** [comment]
Done. Not sure if they are on the repo, but I uploaded from Git Desktop. 
Confirmed?

**Comment by corykitchens** [comment]
Nope. Did you do the following..

1. Created a branch e.g. `feature-sprites` etc
2. `git checkout feature-sprites`
3. Move the files to the `assets/images` directory
4. Add them to the staging area to commit e.g. `git add public/game/assets/images`
5. Commit them `git commit -m "Added sprites"
6. Push them to your remote branch `git push origin feature-sprites`
